# Site settings
title:          Jurnal Harian Regional
description:    "Baca dan download jurnal akademis gratis"
#baseurl:        "/jurnal"
url:            "https://jurnal.harianregional.com"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Jurnal
  url:          https://jurnal.harianregional.com/
  email:        jurnal@harianregional.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # jekyll-last-modified-at
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:categories/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jurnal-harian-regional

# Collections
collections:
  full:
    output: true
    permalink: /:categories/:title
